### ISSUE TITLE
Cannot "ssh-add" since version 1.3

### ISSUE THREAD

**Issue by mbrodala** [docksal/image-ssh-agent#10]
We are using the following service setup in our `docker-compose.yml`:

```yml
version: 3

services:
  ssh-agent:
    image: docksal/ssh-agent:1.2
    volumes:
      - ssh-agent:/.ssh-agent

  ssh-key:
    image: docksal/ssh-agent:1.2
    command: ['bash', '-c', 'ssh-add - </tmp/host-ssh/id_rsa']
    depends_on:
      - ssh-agent
    volumes:
      - $HOME/.ssh:/tmp/host-ssh:ro
      - ssh-agent:/.ssh-agent

volumes:
  ssh-agent:
```

While this works perfectly fine it fails since version 1.3 of this image.

With version 1.2:

```
$ docker-compose ps
                Name                              Command                       State                         Ports               
---------------------------------------------------------------------------------------------------------------------------------- 
project_ssh-agent_1                    docker-entrypoint.sh ssh-agent   Up (healthy)                                     
project_ssh-key_1                      docker-entrypoint.sh bash  ...   Exit 0                                               
```

With version 1.3:

```
$ docker-compose ps
                Name                              Command                       State                         Ports               
---------------------------------------------------------------------------------------------------------------------------------- 
project_ssh-agent_1                    docker-entrypoint.sh ssh-agent   Up (healthy)                                     
project_ssh-key_1                      docker-entrypoint.sh bash  ...   Exit 2                                
$ docker-compose logs ssh-key
Attaching to project_ssh-key_1
ssh-key_1        | Error connecting to agent: No such file or directory
```

The `/.ssh-agent` directory in the `ssh-agent` service looks fine if just that service is (re)started:

```
$ docker-compose exec ssh-agent ls -la /.ssh-agent
total 8
drwxr-xr-x    2 root     root          4096 Oct  7 12:48 .
drwxr-xr-x    1 root     root          4096 Oct  7 12:46 ..
srw-rw-rw-    1 root     root             0 Oct  7 12:48 proxy-socket
srw-------    1 root     root             0 Oct  7 12:48 socket
```

However, as soon as the `ssh-key` service is executed, the socket files in this directory disappear. The logs of `ssh-agent` do not show anything useful:

```
ssh-agent_1      | Creating proxy socket...
ssh-agent_1      | Launching ssh-agent...
ssh-agent_1      | debug2: fd 3 setting O_NONBLOCK
ssh-agent_1      | SSH_AUTH_SOCK=/.ssh-agent/socket; export SSH_AUTH_SOCK;
ssh-agent_1      | echo Agent pid 1;
```

Any idea what's going on? For now we need to stick with version 1.2.

**Comment by lmakarov** [comment]
@mbrodala  Looks like you are using this image outside of it's primary intended use case - with Docksal - which is exciting! Mind sharing some details? :)

> However, as soon as the ssh-key service is executed, the socket files in this directory disappear.

Here's why:
https://github.com/docksal/service-ssh-agent/blob/develop/bin/docker-entrypoint.sh#L8-L9

That line moved in the entrypoint script of the image and is now executed unconditionally. You'd have to override the container ENTRYPOINT in the `ssh-key` service, so the stock one is not triggered, e.g.:

```
version: "3"

services:
  ssh-agent:
    image: docksal/ssh-agent:1.3
    volumes:
      - ssh-agent:/.ssh-agent

  ssh-key:
    image: docksal/ssh-agent:1.3
    entrypoint: ['bash', '-c']
    command: ['ssh-add - </tmp/host-ssh/id_rsa']
    depends_on:
      - ssh-agent
    volumes:
      - $HOME/.ssh:/tmp/host-ssh:ro
      - ssh-agent:/.ssh-agent

volumes:
  ssh-agent:
```

```
$ docker-compose up -d
Creating volume "ssh-agent_ssh-agent" with default driver
Creating ssh-agent_ssh-agent_1 ... done
Creating ssh-agent_ssh-key_1   ... done

$ docker-compose logs
Attaching to ssh-agent_ssh-key_1, ssh-agent_ssh-agent_1
ssh-agent_1  | Creating proxy socket...
ssh-agent_1  | Launching ssh-agent...
ssh-agent_1  | SSH_AUTH_SOCK=/.ssh-agent/socket; export SSH_AUTH_SOCK;
ssh-agent_1  | echo Agent pid 1;
ssh-agent_1  | debug2: fd 3 setting O_NONBLOCK
ssh-agent_1  | debug2: fd 4 setting O_NONBLOCK
ssh-agent_1  | debug1: process_message: socket 1 (fd=4) type 17
ssh-key_1    | Identity added: (stdin) ((stdin))
```
